# Generated by Django 5.0.2 on 2024-02-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2000-02-23'),
            preserve_default=False,
        ),
    ]
